version: '3.7'
x-environment:

services:

  simple-rest-api:
    image: simple-rest-api:latest
    env_file:
      - .env
    environment:
      ACTIVE_PROFILE: prod
    ports:
      - 8080:8080
    networks:
      - simple-network

  simple-react:
    image: simple-react:latest
    ports:
      - 3000:3000
    networks:
      - simple-network
    depends_on:
      - simple-rest-api
        

networks:
  simple-network: